-- ============================================================
-- Migration: 001_initial_setup
-- AUTO-GENERATED by migrations/generate.js — do not edit by hand.
-- Edit schemas.js then re-run: npm run generate:migrations
-- ============================================================

-- Create database if it does not already exist
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'ExampleDB')
BEGIN
    CREATE DATABASE ExampleDB;
END
GO

USE ExampleDB;
GO

-- ============================================================
-- Table: atbl_Example_Users
-- ============================================================
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'atbl_Example_Users' AND xtype = 'U')
BEGIN
    CREATE TABLE atbl_Example_Users (
      PrimKey UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
      Username NVARCHAR(100) NOT NULL,
      Email NVARCHAR(255) NOT NULL,
      Created DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
      Updated DATETIME2 NULL,
      CONSTRAINT PK_atbl_Example_Users PRIMARY KEY (PrimKey),
      CONSTRAINT UQ_atbl_Example_Users_Username UNIQUE (Username)
    );
END
GO

CREATE OR ALTER TRIGGER trg_atbl_Example_Users_Updated
ON atbl_Example_Users
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE atbl_Example_Users
    SET    Updated = SYSDATETIME()
    FROM   atbl_Example_Users t
    INNER JOIN inserted i ON t.PrimKey = i.PrimKey;
END
GO

-- ============================================================
-- Table: atbl_Example_Posts
-- ============================================================
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'atbl_Example_Posts' AND xtype = 'U')
BEGIN
    CREATE TABLE atbl_Example_Posts (
      PrimKey UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
      Author_ID UNIQUEIDENTIFIER NOT NULL,
      Title NVARCHAR(500) NOT NULL,
      Body NVARCHAR(MAX) NULL,
      Created DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
      Updated DATETIME2 NULL,
      CONSTRAINT PK_atbl_Example_Posts PRIMARY KEY (PrimKey),
      CONSTRAINT FK_atbl_Example_Posts_Author_ID FOREIGN KEY (Author_ID) REFERENCES atbl_Example_Users (PrimKey)
    );
END
GO

CREATE OR ALTER TRIGGER trg_atbl_Example_Posts_Updated
ON atbl_Example_Posts
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE atbl_Example_Posts
    SET    Updated = SYSDATETIME()
    FROM   atbl_Example_Posts t
    INNER JOIN inserted i ON t.PrimKey = i.PrimKey;
END
GO

-- ============================================================
-- Table: atbl_Example_Comments
-- ============================================================
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'atbl_Example_Comments' AND xtype = 'U')
BEGIN
    CREATE TABLE atbl_Example_Comments (
      PrimKey UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
      Post_ID UNIQUEIDENTIFIER NOT NULL,
      Author_ID UNIQUEIDENTIFIER NOT NULL,
      Body NVARCHAR(MAX) NOT NULL,
      Created DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
      Updated DATETIME2 NULL,
      CONSTRAINT PK_atbl_Example_Comments PRIMARY KEY (PrimKey),
      CONSTRAINT FK_atbl_Example_Comments_Post_ID FOREIGN KEY (Post_ID) REFERENCES atbl_Example_Posts (PrimKey),
      CONSTRAINT FK_atbl_Example_Comments_Author_ID FOREIGN KEY (Author_ID) REFERENCES atbl_Example_Users (PrimKey)
    );
END
GO

CREATE OR ALTER TRIGGER trg_atbl_Example_Comments_Updated
ON atbl_Example_Comments
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE atbl_Example_Comments
    SET    Updated = SYSDATETIME()
    FROM   atbl_Example_Comments t
    INNER JOIN inserted i ON t.PrimKey = i.PrimKey;
END
GO
