'use strict';

/**
 * migrations/generate.js
 *
 * Regenerates migrations/001_initial_setup.sql from the schemas defined in
 * schemas.js (which in turn use the queryBuilder).
 *
 * Run with:
 *   npm run generate:migrations
 *
 * The output file is committed to version control and is consumed by the SQL
 * Server container's entrypoint (docker/entrypoint.sh) via sqlcmd.
 */

const fs = require('fs');
const path = require('path');
const { Users, Posts, Comments } = require('../schemas');

// All schemas in dependency order (referenced tables must be created first).
const schemas = [Users, Posts, Comments];

// ---------------------------------------------------------------------------
// Header + database bootstrap (static SQL — not schema-specific)
// ---------------------------------------------------------------------------
const header = `\
-- ============================================================
-- Migration: 001_initial_setup
-- AUTO-GENERATED by migrations/generate.js — do not edit by hand.
-- Edit schemas.js then re-run: npm run generate:migrations
-- ============================================================

-- Create database if it does not already exist
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'ExampleDB')
BEGIN
    CREATE DATABASE ExampleDB;
END
GO

USE ExampleDB;
GO
`;

// ---------------------------------------------------------------------------
// Build one SQL block per schema: IF NOT EXISTS guard + CREATE TABLE + trigger
// ---------------------------------------------------------------------------
function buildTableBlock(schema) {
  const createSql = schema.createTable();
  const triggerSql = schema.createUpdateTrigger();

  return `\
-- ============================================================
-- Table: ${schema.tableName}
-- ============================================================
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = '${schema.tableName}' AND xtype = 'U')
BEGIN
${createSql.replace(/^/gm, '    ').trimEnd()}
END
GO

${triggerSql}
GO
`;
}

// ---------------------------------------------------------------------------
// Compose and write the file
// ---------------------------------------------------------------------------
const blocks = schemas.map(buildTableBlock);
const output = header + '\n' + blocks.join('\n');

const outputPath = path.join(__dirname, '001_initial_setup.sql');
fs.writeFileSync(outputPath, output, 'utf8');

console.log(`Generated ${outputPath}`);
